### ISSUE TITLE
if object being proxied already has setter functionality that functionality is lost

### ISSUE THREAD

**Issue by Torinth** [cb1kenobi/gawk#5]
Hi, I was testing gawk in npm runkit and it looks like if you gawk an object that already has getter/setter logic that logic is lost when its replaced.  This would be helpful to be supported so that existing class objects and other  existing functionality could be watched with gawk without having to be refactored.  here is the sample I used in runkit to repro.  the second set of the blah property does not fire the existing setter.

`var gawk = require("gawk")

var innerObj = {};

Object.defineProperty(innerObj, "blah", {
get: () => innerObj._blah,
set: (val) =>{
innerObj._blah = val;
console.info('existing setter called');
},
enumerable: true,
        configurable: true
});

innerObj.blah = "initial";

var obj = gawk.gawk(innerObj);

gawk.watch(obj, () => console.info('changed'));

obj.blah = "somethingelse"`

**Comment by cb1kenobi** [comment]
Thanks for the bug report! Indeed there was an issue. I've fixed it and it will be published as apart of v4.6.0!
